import 'package:flutter_finance_app/purchase.dart';
import 'package:intl/intl.dart';

// Test data for various database functions
class DatabaseData {
  DateTime time0 = DateTime.parse('2023-06-01 01:08:00'),
      time1 = DateTime.parse('2023-06-01 11:41:00'),
      time2 = DateTime.parse('2023-06-02 09:00:00'),
      time3 = DateTime.parse('2023-06-03 04:49:00'),
      time4 = DateTime.parse('2023-06-04 09:03:00'),
      time5 = DateTime.parse('2023-06-04 12:51:00'),
      time6 = DateTime.parse('2023-06-05 07:16:00'),
      time7 = DateTime.parse('2023-06-06 06:33:00'),
      time8 = DateTime.parse('2023-06-06 15:05:00'),
      time9 = DateTime.parse('2023-05-18 01:15:00'),
      time10 = DateTime.parse('2023-05-19 08:27:00'),
      time11 = DateTime.parse('2023-05-21 11:11:00'),
      time12 = DateTime.parse('2023-05-22 16:54:00'),
      time13 = DateTime.parse('2023-05-23 22:01:00'),
      time14 = DateTime.now(),
      time15 = DateTime.now().add(const Duration(hours: 2)),
      time16 = DateTime.now().add(const Duration(hours: 6));

  List<Purchase> data = <Purchase>[];

  DatabaseData() {
    data = <Purchase>[
      Purchase(
          id: 0,
          name: "Burger",
          price: 8.99,
          category: "Food",
          createdAt: time0.millisecondsSinceEpoch,
          year: time0.year,
          month: time0.month,
          day: time0.day,
          weekday: DateFormat('EEEE').format(time0)),
      Purchase(
          id: 1,
          name: "Fries",
          price: 3.99,
          category: "Food",
          createdAt: time1.millisecondsSinceEpoch,
          year: time1.year,
          month: time1.month,
          day: time1.day,
          weekday: DateFormat('EEEE').format(time1)),
      Purchase(
          id: 2,
          name: "Pizza",
          price: 7.50,
          category: "Food",
          createdAt: time2.millisecondsSinceEpoch,
          year: time2.year,
          month: time2.month,
          day: time2.day,
          weekday: DateFormat('EEEE').format(time2)),
      Purchase(
          id: 3,
          name: "Sushi",
          price: 14.99,
          category: "Food",
          createdAt: time3.millisecondsSinceEpoch,
          year: time3.year,
          month: time3.month,
          day: time3.day,
          weekday: DateFormat('EEEE').format(time3)),
      Purchase(
          id: 4,
          name: "Salad",
          price: 8.00,
          category: "Food",
          createdAt: time4.millisecondsSinceEpoch,
          year: time4.year,
          month: time4.month,
          day: time4.day,
          weekday: DateFormat('EEEE').format(time4)),
      Purchase(
          id: 5,
          name: "Sandwich",
          price: 9.20,
          category: "Food",
          createdAt: time5.millisecondsSinceEpoch,
          year: time5.year,
          month: time5.month,
          day: time5.day,
          weekday: DateFormat('EEEE').format(time5)),
      Purchase(
          id: 6,
          name: "Burrito",
          price: 11.60,
          category: "Food",
          createdAt: time6.millisecondsSinceEpoch,
          year: time6.year,
          month: time6.month,
          day: time6.day,
          weekday: DateFormat('EEEE').format(time6)),
      Purchase(
          id: 7,
          name: "Pancakes",
          price: 7.99,
          category: "Food",
          createdAt: time7.millisecondsSinceEpoch,
          year: time7.year,
          month: time7.month,
          day: time7.day,
          weekday: DateFormat('EEEE').format(time7)),
      Purchase(
          id: 8,
          name: "Pizza",
          price: 8.99,
          category: "Food",
          createdAt: time8.millisecondsSinceEpoch,
          year: time8.year,
          month: time8.month,
          day: time8.day,
          weekday: DateFormat('EEEE').format(time8)),
      Purchase(
          id: 9,
          name: "Electric Bill",
          price: 90.70,
          category: "Utilities",
          createdAt: time9.millisecondsSinceEpoch,
          year: time9.year,
          month: time9.month,
          day: time9.day,
          weekday: DateFormat('EEEE').format(time9)),
      Purchase(
          id: 10,
          name: "Fish and Chips",
          price: 11.14,
          category: "Food",
          createdAt: time9.millisecondsSinceEpoch,
          year: time10.year,
          month: time10.month,
          day: time10.day,
          weekday: DateFormat('EEEE').format(time10)),
      Purchase(
          id: 11,
          name: "Gas Bill",
          price: 37.60,
          category: "Utilities",
          createdAt: time11.millisecondsSinceEpoch,
          year: time11.year,
          month: time11.month,
          day: time11.day,
          weekday: DateFormat('EEEE').format(time11)),
      Purchase(
          id: 12,
          name: "Salad",
          price: 13.99,
          category: "Food",
          createdAt: time12.millisecondsSinceEpoch,
          year: time12.year,
          month: time12.month,
          day: time12.day,
          weekday: DateFormat('EEEE').format(time12)),
      Purchase(
          id: 13,
          name: "Tacos",
          price: 9.99,
          category: "Food",
          createdAt: time13.millisecondsSinceEpoch,
          year: time13.year,
          month: time13.month,
          day: time13.day,
          weekday: DateFormat('EEEE').format(time13)),
      Purchase(
          id: 14,
          name: "Burrito",
          price: 5.65,
          category: "Food",
          createdAt: time14.millisecondsSinceEpoch,
          year: time14.year,
          month: time14.month,
          day: time14.day,
          weekday: DateFormat('EEEE').format(time14)),
      Purchase(
          id: 15,
          name: "Rice",
          price: 3.75,
          category: "Food",
          createdAt: time15.millisecondsSinceEpoch,
          year: time15.year,
          month: time15.month,
          day: time15.day,
          weekday: DateFormat('EEEE').format(time15)),
      Purchase(
          id: 16,
          name: "Tea",
          price: 7.80,
          category: "Food",
          createdAt: time16.millisecondsSinceEpoch,
          year: time16.year,
          month: time16.month,
          day: time16.day,
          weekday: DateFormat('EEEE').format(time16))
    ];
  }
}
